### ISSUE TITLE
Criar Banco de dados do microsserviço

### ISSUE THREAD

**Issue by Sayuck** [fga-eps-mds/2022-1-schedula-gestor-de-usuarios#5]
- [x] Criar a model 
- [x] Criar sql

**Comment by brun0sk** [comment]
Banco adicionado na branch 5_criar_DB.

**Comment by Matheus73** [comment]
@brun0sk Por favor abra um pull request para a branch `develop` e me marque como revisor.

**Comment by brun0sk** [comment]
Foi criada a model, branch 5_DB_Model.
